### ISSUE TITLE
Commander calls

### ISSUE THREAD

**Issue by nrWillbanks** [brianchuchua/asoiaf-tmg-discord-bot#9]
Would be cool if calling a commander (without any additional search words to specify further) brought up their Attachment Card & all 3/4 Tactics Cards by default.

**Comment by brianchuchua** [comment]
This is an interesting feature request!

I don't think I should do this new behavior by default since there are already a few people on the fence about the fronts and backs of cards showing by default. There's sensitivity to too many images coming up already, and there's no way for me to do them side by side, so they would be each on their own line.

However, I could so something like `!a jaime -all`, where the `-all` would tell the system:

"Just look a _Commander_ card that has 'jaime' in its name and then list all of its corresponding tactics cards."

I could run into corner cases where the search query isn't unambiguous enough and there are duplicates, but I can handle that with messaging the user.

The biggest "challenge" for this is a data entry one. I need to teach the bot which commander cards relate to which tactics cards. I could go loosely by the search term but this can run into ambiguities or corner cases so it's best to make that relationship explicit.

I'll do this one when I have some time. :)

**Comment by brianchuchua** [comment]
I went ahead and implemented this.

I tested it a bit and I believe I handle the Brynden situation correctly (there are two commanders, so the user has to do an unambiguous search to have the feature work.)

Give it a whirl, @nrWillbanks . :)

`!a jaime -all`
